"""[WORKFLOW-C.F5 2026-09-15] J.10 features inventory helper.

Per the 2026-09-15 production deep audit F-5: PR #89-#92
features were deployed but invisible in production runtime.
The audit observed 0 log lines for J.10 capture gate
features (MIN_THRESHOLD, FRESHNESS, DEDUP, BRANCH_HISTOGRAM),
WRITE_ATOMIC, etc. because no captures happened that day --
the features are wired but only fire on specific events.

This module gives operators a single command that, when
run, prints the full list of J.10 features wired into this
engine version, so a future audit can confirm wiring
without needing captures to happen.

The inventory is a structured list of dicts:
  - feature_id: stable identifier (e.g. "J.10.DEDUP")
  - added_at: ISO date when the feature was added
  - description: human-readable one-line description
  - cli_flags: list of CLI flags that trigger the feature

No new dependencies -- this is a constant table plus a
helper that formats it for stdout.
"""
from __future__ import annotations

import json
from typing import Any


# Each row is the canonical record for a J.10 feature.
# New features should be added here as a single source of
# truth -- the CLI --features-inventory subcommand reads
# this and prints it.
FEATURES_INVENTORY: tuple[dict[str, Any], ...] = (
    {
        "feature_id": "J.10.GATE",
        "added_at": "2026-09-13",
        "description": (
            "CAS-branch reachability gate: 6 sub-window branches "
            "+ DERIVATIVES_CAS_ALIGNED require real broker evidence."
        ),
        "cli_flags": ["--json", "--write", "--status"],
    },
    {
        "feature_id": "J.10.SUMMARY",
        "added_at": "2026-09-13",
        "description": (
            "Persistent operator-facing SUMMARY.md audit surface. "
            "Generated by --update-summary."
        ),
        "cli_flags": ["--update-summary", "--summary-path"],
    },
    {
        "feature_id": "J.10.DEDUP",
        "added_at": "2026-09-14",
        "description": (
            "Per-branch SHA-256 fingerprint dedup. Counts unique "
            "captures per branch; duplicates_by_branch surfaces the count."
        ),
        "cli_flags": [],
    },
    {
        "feature_id": "J.10.FRESHNESS",
        "added_at": "2026-09-14",
        "description": (
            "Freshness filter: only count captures within max_age_days. "
            "captures_skipped_stale surfaces the skipped count."
        ),
        "cli_flags": ["--captures-since"],
    },
    {
        "feature_id": "J.10.MIN_THRESHOLD",
        "added_at": "2026-09-14",
        "description": (
            "Per-branch minimum UNIQUE capture count for REACHABLE verdict. "
            "Defends against single flaky captures flipping the gate."
        ),
        "cli_flags": ["--min-unique-per-branch"],
    },
    {
        "feature_id": "J.10.CAPTURE_SUMMARY_AGGREGATE",
        "added_at": "2026-09-14",
        "description": (
            "Per-day histogram: date -> {scanned, unique}."
        ),
        "cli_flags": [],
    },
    {
        "feature_id": "J.10.WRITE_ATOMIC",
        "added_at": "2026-09-14",
        "description": (
            "Atomic + byte-identical JSON writes for reachability.json. "
            "Mirrors reconciliation_cli _write_output_atomic (F5 discipline)."
        ),
        "cli_flags": [],
    },
    {
        "feature_id": "J.10.BRANCH_HISTOGRAM",
        "added_at": "2026-09-14",
        "description": (
            "Per-branch-per-day matrix in SUMMARY.md and JSON."
        ),
        "cli_flags": ["--show-branch-histogram"],
    },
    {
        "feature_id": "J.10.CAPTURE_LISTING",
        "added_at": "2026-09-14",
        "description": (
            "Side-effect-free listing of every capture on disk, "
            "grouped by branch."
        ),
        "cli_flags": ["--list-captures"],
    },
    {
        "feature_id": "J.10.SUMMARY_VERIFY",
        "added_at": "2026-09-14",
        "description": (
            "Render SUMMARY.md fresh and diff against on-disk file. "
            "Exit codes 0/1/2 (match/real-drift/missing)."
        ),
        "cli_flags": ["--verify-summary"],
    },
    {
        "feature_id": "J.10.CAPTURE_OLDEST_NEWEST",
        "added_at": "2026-09-15",
        "description": (
            "Per-branch oldest/newest capture timestamp + span_days. "
            "Surfaces in SUMMARY.md '## Capture recency' section."
        ),
        "cli_flags": [],
    },
    {
        "feature_id": "J.10.FEATURES_INVENTORY",
        "added_at": "2026-09-15",
        "description": (
            "Self-describing CLI: --features-inventory prints this "
            "list. Lets operators confirm wiring without needing "
            "captures to happen. (Added per F-5 from the 2026-09-15 "
            "production audit: PR #89-#92 features deployed but "
            "invisible in runtime -- the inventory gives a "
            "capture-free wiring signal.)"
        ),
        "cli_flags": ["--features-inventory"],
    },
)


def format_features_inventory(features: tuple[dict[str, Any], ...] = FEATURES_INVENTORY) -> str:
    """Render the inventory as a human-readable table.

    Returns a string with one row per feature, sorted by
    feature_id for stable display.
    """
    rows = sorted(features, key=lambda f: f["feature_id"])
    lines = [
        "# J.10 features inventory",
        "# ------------------------",
        "# This engine version ships the following J.10 features.",
        "# Use this to confirm wiring without needing captures to happen.",
        "# Run with --json for machine-readable output.",
        "",
        f"{'FEATURE_ID':<40}  {'ADDED_AT':<12}  CLI_FLAGS",
        f"{'-' * 40}  {'-' * 12}  {'-' * 50}",
    ]
    for feat in rows:
        flags = ", ".join(feat.get("cli_flags") or []) or "-"
        lines.append(
            f"{feat['feature_id']:<40}  {feat['added_at']:<12}  {flags}"
        )
        lines.append(f"    {feat['description']}")
        lines.append("")
    lines.append(f"# Total: {len(rows)} features wired in this engine version.")
    return "\n".join(lines) + "\n"


def features_inventory_as_json(features: tuple[dict[str, Any], ...] = FEATURES_INVENTORY) -> str:
    """Render the inventory as machine-readable JSON."""
    return json.dumps(
        {"count": len(features), "features": list(features)},
        indent=2,
        sort_keys=True,
    ) + "\n"


__all__ = [
    "FEATURES_INVENTORY",
    "format_features_inventory",
    "features_inventory_as_json",
]
