"""[WORKFLOW-J.10.CLOSURE 2026-09-13] Tests for the operator-facing
SUMMARY.md surface on the J.10 CAS-branch reachability gate.

The SUMMARY.md is the persistent, human-readable surface for
the J.10 gate verdict. It is regenerated by the
``--update-summary`` CLI flag (and by the
``j2_capture_review.py`` happy-path) so operators see the
latest verdict and the missing-branches list without re-running
the CLI.

The contract:

  1. ``SUMMARY.md`` is a deterministic render of the gate's
     report -- verdict, coverage, captured per branch,
     missing branches.
  2. ``update_summary`` is idempotent -- running twice with
     no captures changed produces the same bytes except for
     the ``generated_at_utc`` timestamp.
  3. The SUMMARY.md never claims REACHABLE when the gate is
     UNREACHABLE. Fail-closed.
  4. The SUMMARY.md always lists every required branch with
     its count, even when the gate is UNREACHABLE -- so
     operators can see at a glance what's still missing.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from cas_reachability_gate import (
    CAS_BRANCHES_REQUIRING_EVIDENCE,
    cas_reachability_report,
    update_summary,
)


def test_summary_documents_unreachable_when_no_captures(tmp_path):
    """An empty captures directory produces a SUMMARY.md that
    clearly states UNREACHABLE and lists the missing branches.
    """
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # The verdict line is ``**UNREACHABLE** -- coverage ...``.
    # The prose instructions section may say "REACHABLE" in
    # flow text, but the verdict line MUST start with bold
    # UNREACHABLE.
    verdict_line = next(
        line for line in text.splitlines()
        if line.startswith("**") and "-- coverage" in line
    )
    assert "**UNREACHABLE**" in verdict_line
    # All six required branches listed.
    for branch in CAS_BRANCHES_REQUIRING_EVIDENCE:
        assert branch in text, f"SUMMARY.md missing required branch: {branch}"
    # The "missing" branch section is explicit.
    assert "missing" in text.lower()


def test_summary_documents_reachable_when_all_branches_covered(tmp_path):
    """A directory with one capture per branch produces a SUMMARY.md
    that states REACHABLE with full coverage.
    """
    day = tmp_path / "2026-09-10"
    day.mkdir()
    for branch in CAS_BRANCHES_REQUIRING_EVIDENCE:
        cap = day / f"RELIANCE_{branch}.json"
        cap.write_text(
            '{"schema_version": 2, "rows": [{"classifier_phase": "%s"}]}' % branch,
            encoding="utf-8",
        )
    report = cas_reachability_report(captures_dir=tmp_path)
    assert report["verdict"] == "REACHABLE"
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # Verdict line shows bold REACHABLE.
    verdict_line = next(
        line for line in text.splitlines()
        if line.startswith("**") and "-- coverage" in line
    )
    assert "**REACHABLE**" in verdict_line
    assert "100.0%" in verdict_line
    # When REACHABLE, the missing-branches section is omitted.
    assert "missing branches" not in text.lower()


def test_summary_documents_partial_coverage(tmp_path):
    """A directory with only some branches produces a SUMMARY.md
    with the right missing-branches list.
    """
    day = tmp_path / "2026-09-10"
    day.mkdir()
    captured = ("CAS_REFERENCE_PRICE_WINDOW", "CAS_ORDER_ENTRY")
    for branch in captured:
        cap = day / f"RELIANCE_{branch}.json"
        cap.write_text(
            '{"schema_version": 2, "rows": [{"classifier_phase": "%s"}]}' % branch,
            encoding="utf-8",
        )
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    assert "UNREACHABLE" in text
    # Captured branches are NOT in the missing list.
    for branch in captured:
        assert branch not in _missing_section(text), \
            f"{branch} captured but listed as missing"
    # Uncovered branches ARE in the missing list.
    for branch in CAS_BRANCHES_REQUIRING_EVIDENCE:
        if branch not in captured:
            assert branch in _missing_section(text), \
                f"{branch} not captured but not listed as missing"


def test_summary_lists_per_branch_counts(tmp_path):
    """Each captured branch's count is shown in the SUMMARY."""
    day = tmp_path / "2026-09-10"
    day.mkdir()
    # Two DISTINCT captures of CAS_ORDER_ENTRY (different
    # observation_at so the fingerprints differ -- the dedup
    # contract is that unique observations count, not files),
    # one of CAS_MATCHING.
    (day / "a.json").write_text(
        '{"schema_version": 2, '
        '"observation_at_utc": "2026-09-10T09:51:00+00:00", '
        '"rows": [{"classifier_phase": "CAS_ORDER_ENTRY"}]}',
        encoding="utf-8",
    )
    (day / "b.json").write_text(
        '{"schema_version": 2, '
        '"observation_at_utc": "2026-09-10T09:53:00+00:00", '
        '"rows": [{"classifier_phase": "CAS_ORDER_ENTRY"}]}',
        encoding="utf-8",
    )
    (day / "c.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_MATCHING"}]}',
        encoding="utf-8",
    )
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # Format: ``| CAS_ORDER_ENTRY | 2 (yes) |``. The count and
    # the marker (yes = captured, no = not captured) are
    # visible per branch.
    assert "| CAS_ORDER_ENTRY | 2 (yes) |" in text


def test_summary_includes_captures_catalog_section(tmp_path):
    """The SUMMARY shows a per-branch catalog so operators can
    see exactly which capture paths back each branch. Branches
    with no captures render ``(no captures yet)`` so the gap
    is explicit.
    """
    day = tmp_path / "2026-09-10"
    day.mkdir()
    (day / "RELIANCE_15_15.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_REFERENCE_PRICE_WINDOW"}]}',
        encoding="utf-8",
    )
    (day / "RELIANCE_15_17.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_ORDER_ENTRY"}]}',
        encoding="utf-8",
    )
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")

    # Catalog section heading is rendered.
    assert "## Captures catalog" in text
    # Each branch has a sub-heading (CAS_*, DERIVATIVES_CAS_ALIGNED).
    assert "### CAS_REFERENCE_PRICE_WINDOW" in text
    assert "### CAS_ORDER_ENTRY" in text
    assert "### CAS_LIMIT_ENTRY_ONLY" in text
    assert "### CAS_MATCHING" in text
    assert "### CAS_POST" in text
    assert "### DERIVATIVES_CAS_ALIGNED" in text
    # Captured branches list their relative paths.
    assert "RELIANCE_15_15.json" in text
    assert "RELIANCE_15_17.json" in text
    # Branches with zero captures render the explicit gap marker.
    assert "(no captures yet)" in text


def test_gate_report_includes_captures_by_branch(tmp_path):
    """The gate's report dict carries ``captures_by_branch`` --
    a per-branch list of relative paths. This is the source of
    truth that the SUMMARY catalog section renders.
    """
    day = tmp_path / "2026-09-10"
    day.mkdir()
    (day / "x.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_ORDER_ENTRY"}]}',
        encoding="utf-8",
    )
    report = cas_reachability_report(captures_dir=tmp_path)
    # All 6 branches present, even with empty lists.
    assert set(report["captures_by_branch"].keys()) == set(
        CAS_BRANCHES_REQUIRING_EVIDENCE
    )
    # Captured branch lists the relative path. Use a tail-match
    # because Windows uses backslashes in relative paths while
    # POSIX uses forward slashes.
    captured_paths = report["captures_by_branch"]["CAS_ORDER_ENTRY"]
    assert any(p.endswith("x.json") for p in captured_paths), captured_paths
    # Non-captured branches have empty lists.
    assert report["captures_by_branch"]["CAS_REFERENCE_PRICE_WINDOW"] == []
    assert report["captures_by_branch"]["DERIVATIVES_CAS_ALIGNED"] == []


def test_gate_handles_non_captures_root_path_defensively(tmp_path):
    """A capture outside the captures_root must not crash the
    gate. The catalog falls back to the absolute path so the
    SUMMARY stays useful even when a capture lives in an
    unexpected location.
    """
    captures_root = tmp_path / "docs" / "j2_captures"
    captures_root.mkdir(parents=True)
    other_dir = tmp_path / "elsewhere"
    other_dir.mkdir()
    (other_dir / "RELIANCE_CAS.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_REFERENCE_PRICE_WINDOW"}]}',
        encoding="utf-8",
    )
    report = cas_reachability_report(captures_dir=captures_root)
    # The gate did NOT recurse into ``elsewhere`` because
    # rglob walks the captures_root only -- the file outside
    # is invisible. The branch is still uncaptured.
    assert report["captured_phases"]["CAS_REFERENCE_PRICE_WINDOW"] == 0
    assert report["verdict"] == "UNREACHABLE"

    # Now drop the capture INTO the captures_root via rglob's
    # path: a capture path that's not relative to the root
    # can still be reported if the gate happens to enumerate
    # it (e.g. via operator-supplied override -- future work).
    # For now, the gate is robust to the simple case above.
    (captures_root / "RELIANCE_CAS_REFERENCE.json").write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_REFERENCE_PRICE_WINDOW"}]}',
        encoding="utf-8",
    )
    report2 = cas_reachability_report(captures_dir=captures_root)
    # Tail-match the relative path (Windows uses backslashes).
    captured_paths2 = (
        report2["captures_by_branch"]["CAS_REFERENCE_PRICE_WINDOW"]
    )
    assert any(
        p.endswith("RELIANCE_CAS_REFERENCE.json") for p in captured_paths2
    ), captured_paths2


def test_summary_never_claims_reachable_when_missing_branches(tmp_path):
    """Fail-closed: even if the operator mistakenly writes
    SUMMARY.md claiming REACHABLE, the gate's ``update_summary``
    never produces that -- it always reflects the gate verdict.
    """
    day = tmp_path / "2026-09-10"
    day.mkdir()
    # Only one branch covered.
    cap = day / "RELIANCE_CAS_REFERENCE_PRICE_WINDOW.json"
    cap.write_text(
        '{"schema_version": 2, "rows": [{"classifier_phase": "CAS_REFERENCE_PRICE_WINDOW"}]}',
        encoding="utf-8",
    )
    report = cas_reachability_report(captures_dir=tmp_path)
    assert report["verdict"] == "UNREACHABLE"
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # Fail-closed: the verdict line shows bold UNREACHABLE.
    verdict_line = next(
        line for line in text.splitlines()
        if line.startswith("**") and "-- coverage" in line
    )
    assert "**UNREACHABLE**" in verdict_line


def test_update_summary_is_idempotent(tmp_path):
    """Running ``update_summary`` twice with the same report
    produces byte-identical files except for the
    ``generated_at_utc`` timestamp.
    """
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    first = summary_path.read_text(encoding="utf-8")
    update_summary(report, summary_path=summary_path)
    second = summary_path.read_text(encoding="utf-8")
    # Strip the timestamp line for comparison (we can't make it
    # deterministic without faking the clock; rule out drift
    # everywhere else).
    def _strip_ts(s: str) -> str:
        return "\n".join(
            line for line in s.splitlines()
            if not line.startswith("**Generated at")
        )
    assert _strip_ts(first) == _strip_ts(second)


def test_summary_includes_generated_at_timestamp(tmp_path):
    """The SUMMARY.md carries a ``Generated at`` marker so
    operators can see when it was last regenerated.
    """
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # The marker text is ``**Generated at**: `` -- bold + colon.
    # Asserting on the visible marker text (without markdown
    # markers) keeps the test stable across template refactors.
    assert "Generated at" in text
    assert "UTC" in text  # timestamp is ISO 8601 with timezone


def test_summary_includes_path_to_captures_directory(tmp_path):
    """The SUMMARY.md references the captures directory so
    operators can find the source data.
    """
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path,
                   captures_dir=tmp_path)
    text = summary_path.read_text(encoding="utf-8")
    assert str(tmp_path) in text


def test_summary_mentions_j10_review_tool(tmp_path):
    """The SUMMARY.md points operators to the review tool
    so they know how to validate new captures.
    """
    report = cas_reachability_report(captures_dir=tmp_path)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    text = summary_path.read_text(encoding="utf-8")
    # The review tool is the standard way to validate captures;
    # operators should see this in the SUMMARY so they know
    # where to look.
    assert "j2_capture_review" in text


def test_summary_never_raises_on_missing_captures_dir(tmp_path):
    """If ``captures_dir`` doesn't exist, ``update_summary``
    still produces a valid SUMMARY.md (the same UNREACHABLE
    document it would produce for an empty directory).
    """
    missing = tmp_path / "no_such_dir"
    report = cas_reachability_report(captures_dir=missing)
    summary_path = tmp_path / "SUMMARY.md"
    update_summary(report, summary_path=summary_path)
    assert summary_path.exists()
    text = summary_path.read_text(encoding="utf-8")
    assert "UNREACHABLE" in text


def _missing_section(text: str) -> str:
    """Return the section of a SUMMARY.md that lists missing
    branches. Used to assert that captured branches do NOT
    appear in the missing list.
    """
    lines = text.splitlines()
    start = None
    end = len(lines)
    for i, line in enumerate(lines):
        if "missing" in line.lower() and ("branch" in line.lower() or "phase" in line.lower()):
            start = i + 1
            break
    if start is None:
        return ""
    for i in range(start, len(lines)):
        if lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])
