"""Regenerate the source navigation appendix without importing application code."""
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs' / 'SYSTEM_CODE_ATLAS.md'


def build():
    lines = ['# System code atlas', '',
        'Generated by `python scripts/build_system_code_atlas.py`. Source navigation, not runtime verification.',
        'Read SYSTEM_GUIDE.md for architecture and NEXT_AGENT_PLAN.md for priorities. Paths are repository-relative.',
        'Module descriptions below are source-declared intent; inspect implementation and tests before relying on them.', '']
    files = sorted(list((ROOT / 'python-engine').glob('*.py')) + list((ROOT / 'agent').glob('*.py')))
    for path in files:
        source = path.read_text(encoding='utf-8-sig')
        tree = ast.parse(source)
        rel = path.relative_to(ROOT).as_posix()
        lines += [f'## `{rel}`', '']
        doc = ast.get_docstring(tree)
        lines += [(' '.join(doc.split())[:700].rstrip() if doc else 'No module docstring; use the declarations and callers below.'), '']
        definitions = [f'`{node.name}` (line {node.lineno})' for node in tree.body
                       if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
        lines += ['Top-level declarations: ' + (', '.join(definitions) or 'none'), '']
        imports = sorted({node.module for node in ast.walk(tree) if isinstance(node, ast.ImportFrom)
                          and node.module and (ROOT / 'python-engine' / (node.module.split('.')[0] + '.py')).exists()})
        if imports:
            lines += ['Engine dependencies: ' + ', '.join(f'`{name}`' for name in imports), '']
        tests = sorted((ROOT / path.parts[-2] / 'tests').glob(f'test_{path.stem}*.py'))
        if tests:
            lines += ['Related tests: ' + ', '.join(f'`{p.relative_to(ROOT).as_posix()}`' for p in tests), '']
        tables = sorted(set(re.findall(r'CREATE TABLE IF NOT EXISTS\s+([A-Za-z_][A-Za-z_0-9]*)', source, re.I)))
        if tables:
            lines += ['Declared tables: ' + ', '.join(f'`{name}`' for name in tables), '']
    lines += ['# Gateway and dashboard source', '', 'Imports/requires describe dependencies; route mounting and authentication must be checked in app.js and the router.', '']
    for folder in ('node-gateway/server', 'node-gateway/client/src'):
        for path in sorted((ROOT / folder).rglob('*')):
            if path.suffix not in {'.js', '.jsx', '.sql', '.css'} or any(part in {'node_modules', '__tests__', 'tests', 'dist'} for part in path.parts):
                continue
            source = path.read_text(encoding='utf-8-sig')
            imports = sorted(set(re.findall(r'(?:from\s+|require\()[\'"]([^\'"]+)', source)))
            lines += [f'## `{path.relative_to(ROOT).as_posix()}`', '',
                      'Dependencies: ' + (', '.join(f'`{name}`' for name in imports) or 'none extracted'), '']
            routes = re.findall(r'(?:router|app)\.(get|post|put|patch|delete)\(\s*[\'"]([^\'"]+)', source)
            if routes:
                lines += ['Local routes: ' + ', '.join(f'`{verb.upper()} {route}`' for verb, route in routes), '']
    lines += ['# Change workflow', '',
              'Regenerate this appendix whenever source declarations/files change; update the narrative guide and plan manually.',
              'Do not treat generated import lists or test filenames as proof of behavior or release readiness.', '']
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'{OUTPUT}: {len(files)} Python modules indexed')


if __name__ == '__main__':
    build()
