#!/usr/bin/env python3
"""[WORKFLOW-D.3 2026-09-16] Auto-generate RELEASE_NOTES.md
from git log + audit artifacts.

Per Workstream D item 3 in NEXT_AGENT_PLAN.md:
> 3. Prepare a PR describing behavior, tests and remaining
>    operational prerequisites. User authorization is required
>    for actions outside existing scope, including actual
>    partner messages or live canary orders.

This script is the bounded dev-side slice of D.3. It
auto-generates the PR description's technical sections
from git + the D.1 / D.2.a audit outputs. The operator
still owns:
  - The PR title and human-readable summary.
  - Authorization for live deploy / partner messages.
  - Manual sign-off on the generated notes.

The output is deterministic. The same git SHA produces
the same notes byte-for-byte (modulo git's commit-time
formatting).

Usage:
    python scripts/build_release_notes.py
    python scripts/build_release_notes.py --base-ref main
    python scripts/build_release_notes.py --out RELEASE_NOTES.md
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent


# Regex helpers.
_COMMIT_LINE_RE = re.compile(
    r"^(?P<sha>[0-9a-f]{7,40})\s+(?P<subject>.+?)$"
)


def _run_git(*args: str, cwd: Path | None = None) -> str:
    """Run a git command and return stdout. Empty string on failure."""
    proc = subprocess.run(
        ["git", *args],
        cwd=str(cwd or REPO_ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if proc.returncode != 0:
        return ""
    return proc.stdout


def get_git_state(repo: Path) -> dict[str, Any]:
    """Capture the current git state for the release notes."""
    head_sha = _run_git("rev-parse", "HEAD", cwd=repo).strip()
    head_short = _run_git("rev-parse", "--short", "HEAD", cwd=repo).strip()
    branch = _run_git("rev-parse", "--abbrev-ref", "HEAD", cwd=repo).strip()
    # Commits since base_ref (default: last 30).
    commits_raw = _run_git("log", "--oneline", "-30", cwd=repo)
    commits: list[dict] = []
    for line in commits_raw.splitlines():
        m = _COMMIT_LINE_RE.match(line.strip())
        if m:
            commits.append({
                "sha": m.group("sha"),
                "subject": m.group("subject"),
            })
    # Tags.
    tags_raw = _run_git("tag", "--sort=-creatordate", cwd=repo)
    tags = [t for t in tags_raw.splitlines() if t.strip()][:10]
    # Working-tree status.
    status_raw = _run_git("status", "--short", cwd=repo)
    uncommitted = [s for s in status_raw.splitlines() if s.strip()]
    return {
        "head_sha": head_sha,
        "head_short": head_short,
        "branch": branch,
        "commits": commits,
        "tags": tags,
        "uncommitted_files": uncommitted,
    }


def categorize_commit(subject: str) -> str:
    """Map a commit subject to a category.

    Categories mirror the conventional commits used by this
    branch:
      - feat: new feature
      - fix: bug fix
      - docs: documentation
      - refactor: no behaviour change
      - test: test-only change
      - chore: build / infra / tooling
      - other: anything else
    """
    lowered = subject.lower()
    if lowered.startswith("feat") or lowered.startswith("feature"):
        return "feat"
    if lowered.startswith("fix"):
        return "fix"
    if lowered.startswith("docs"):
        return "docs"
    if lowered.startswith("refactor"):
        return "refactor"
    if lowered.startswith("test"):
        return "test"
    if lowered.startswith("chore"):
        return "chore"
    return "other"


def render_release_notes(
    git_state: dict[str, Any],
    *,
    base_ref: str = "",
    test_receipt: dict[str, Any] | None = None,
    migration_ledger: dict[str, Any] | None = None,
    defaults_audit: dict[str, Any] | None = None,
) -> str:
    """Render the release notes markdown.

    Args:
        git_state: output of ``get_git_state``.
        base_ref: the base branch (e.g. ``main``) used for
            comparison. Defaults to empty (no diff).
        test_receipt: optional dict from D.1 receipt.
        migration_ledger: optional dict from D.2.a-migrations.
        defaults_audit: optional dict from D.2.a-flags.
    """
    lines: list[str] = []
    lines.append("# Release notes")
    lines.append("")
    lines.append("> Auto-generated by ``scripts/build_release_notes.py``. The")
    lines.append("> operator reviews + signs off before this becomes the PR body.")
    lines.append("")
    lines.append(f"- **Branch**: `{git_state['branch']}`")
    lines.append(f"- **Head SHA**: `{git_state['head_short']}` "
                 f"(full: `{git_state['head_sha']}`)")
    if base_ref:
        lines.append(f"- **Base ref**: `{base_ref}`")
    if git_state["tags"]:
        lines.append(f"- **Recent tags**: {', '.join(git_state['tags'][:5])}")
    if git_state["uncommitted_files"]:
        lines.append(f"- **Uncommitted changes**: {len(git_state['uncommitted_files'])} files")
    lines.append("")

    # Commit summary by category.
    by_category: dict[str, list[dict]] = {}
    for c in git_state["commits"]:
        cat = categorize_commit(c["subject"])
        by_category.setdefault(cat, []).append(c)

    lines.append("## Commits in this release")
    lines.append("")
    lines.append(f"Total: **{len(git_state['commits'])}** commits.")
    lines.append("")
    # Show count by category first.
    cat_order = ["feat", "fix", "docs", "refactor", "test", "chore", "other"]
    for cat in cat_order:
        n = len(by_category.get(cat, []))
        if n:
            lines.append(f"- **{cat}**: {n}")
    lines.append("")

    # Detailed list (newest first).
    for c in reversed(git_state["commits"]):
        cat = categorize_commit(c["subject"])
        lines.append(f"- `{c['sha']}` ({cat}): {c['subject']}")
    lines.append("")

    # Test receipt (D.1).
    if test_receipt:
        lines.append("## Test health (from D.1 release-readiness receipt)")
        lines.append("")
        if isinstance(test_receipt, dict):
            for key, value in test_receipt.items():
                lines.append(f"- **{key}**: {value}")
        else:
            lines.append(str(test_receipt))
        lines.append("")

    # Migration ledger (D.2.a-migrations).
    if migration_ledger:
        tables_count = migration_ledger.get("tables_count", "?")
        migrations_count = migration_ledger.get("migrations_count", "?")
        lines.append("## Migration ledger (from D.2.a-migrations)")
        lines.append("")
        lines.append(f"- Tables discovered: **{tables_count}**")
        lines.append(f"- Migration steps: **{migrations_count}**")
        schema_constants = migration_ledger.get("schema_constants", {})
        if schema_constants:
            lines.append(f"- Modules using ``db.executescript(_SCHEMA)``: **{len(schema_constants)}**")
        lines.append("")

    # Defaults audit (D.2.a-flags).
    if defaults_audit and isinstance(defaults_audit, list):
        risky = [r for r in defaults_audit if r.get("tier") == "RISKY"]
        infra = [r for r in defaults_audit if r.get("tier") == "INFRASTRUCTURE"]
        safe = [r for r in defaults_audit if r.get("tier") == "SAFE"]
        lines.append("## Defaults audit (from D.2.a-flags)")
        lines.append("")
        lines.append(f"- Total rows: **{len(defaults_audit)}**")
        lines.append(f"- **RISKY** (operator must review): **{len(risky)}**")
        lines.append(f"- INFRASTRUCTURE (deployment-level): **{len(infra)}**")
        lines.append(f"- SAFE: **{len(safe)}**")
        if risky:
            lines.append("")
            lines.append("**RISKY settings that require review:**")
            lines.append("")
            for r in risky[:20]:  # Cap at 20 to keep the doc bounded.
                lines.append(f"- `{r['name']}` = `{r['default']}` -- {r['reason']}")
            if len(risky) > 20:
                lines.append(f"- (... and {len(risky) - 20} more; "
                             f"see ``scripts/audit_defaults.py --risky-only``)")
        lines.append("")

    # Operator checklist.
    lines.append("## Operator checklist (pre-deploy)")
    lines.append("")
    lines.append("- [ ] Reviewed all RISKY defaults in the audit above")
    lines.append("- [ ] Migration ledger cross-checked against production schema")
    lines.append("- [ ] Test health snapshot reviewed (D.1)")
    lines.append("- [ ] Live deployment authorized per ``deployment-verification-runbook.md``")
    lines.append("- [ ] Post-deploy: run ``scripts/verify_deployment.py --expected-sha "
                 f"{git_state['head_sha']}``")
    lines.append("")

    lines.append("## Operator checklist (post-deploy)")
    lines.append("")
    lines.append("- [ ] Confirm live container SHA matches HEAD")
    lines.append("- [ ] Confirm /api/health reports the expected SHA")
    lines.append("- [ ] Confirm no errors in the first 10 minutes of logs")
    lines.append("- [ ] Confirm the daily audit runs cleanly tomorrow")
    lines.append("")

    return "\n".join(lines) + "\n"


def _try_load_json(path: Path) -> Any | None:
    """Load JSON from a file if it exists; otherwise return None."""
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=REPO_ROOT,
                        help="Path to the trading-sentinel repo.")
    parser.add_argument("--base-ref", default="",
                        help="Base ref (e.g. ``main``) for diff context.")
    parser.add_argument("--test-receipt", type=Path, default=None,
                        help="Path to D.1 test receipt JSON.")
    parser.add_argument("--migration-ledger", type=Path, default=None,
                        help="Path to D.2.a-migrations JSON output.")
    parser.add_argument("--defaults-audit", type=Path, default=None,
                        help="Path to D.2.a-flags JSON output.")
    parser.add_argument("--out", type=Path, default=None,
                        help="Write the notes to this path.")
    args = parser.parse_args(argv)
    if not args.repo.is_dir():
        print(f"build_release_notes: not a directory: {args.repo}",
              file=sys.stderr)
        return 2
    git_state = get_git_state(args.repo)
    test_receipt = _try_load_json(args.test_receipt) if args.test_receipt else None
    migration_ledger_data = _try_load_json(args.migration_ledger) if args.migration_ledger else None
    if migration_ledger_data and "ledger" in migration_ledger_data:
        migration_ledger = migration_ledger_data["ledger"]
    else:
        migration_ledger = migration_ledger_data
    defaults_audit_data = _try_load_json(args.defaults_audit) if args.defaults_audit else None
    notes = render_release_notes(
        git_state,
        base_ref=args.base_ref,
        test_receipt=test_receipt,
        migration_ledger=migration_ledger,
        defaults_audit=defaults_audit_data,
    )
    sys.stdout.write(notes)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(notes, encoding="utf-8")
    return 0


__all__ = [
    "categorize_commit",
    "get_git_state",
    "main",
    "render_release_notes",
]


if __name__ == "__main__":
    raise SystemExit(main())
